#+title: COSC 200
#+author: Jason Press

This is Jason Press and Mia Stulac's project for COSC 200

* Setup

For ~bootstrap.py~ to run, the following packages must be installed (note: versions can be earlier, I just don't care to find out what versions are good):

- [[https://musescore.org/en][Musescore 4.3+]]
- [[https://nodejs.org/en][Node.js]] (or npx)
- ~bash~, but this should be a part Linux/Mac systems already
- [[https://www.python.org/][Python 3.11+]]

You can check if the packages are installed by running the following commands:

#+begin_src:
mscore --version
npx --version
python3 --version
#+end_src

Git clone this repo.

Ensure ~dl-librescore~ is installed by running ~npx dl-librescore~. If this is the first time running it, it should install some packages and do its thing. Once a dialog appears asking for a file, you can stop the process (~C-c~).

Ensure ~mscore~ is a part of ~$PATH~. If ~mscore --version~ shows a version of Musescore, then you're good. If not, add it to your ~$PATH~.

Run ~src/bootstrap.py~ (you can execute ~python3 bootstrap.py~ in the src directory). It will create the ~/data~ directory inside the project.

* What is left to do?

1. Add a bunch of Musescore URLs to ~src/url.txt~, each URL on its own line
2. Write a Python script that loads the training data
   - Done, kinda. It's jank. This whole project is jank
3. Write the neural network optimizer
