#+title: COSC 200
#+author: Jason Press

This is Jason Press and Mia Stulac's project for COSC 200. Although I don't know if Mia Stulac is caring about this anymore, so I guess it's just Jason Press (?)

This project is training a neural network to upscale scanned scores.

* Setup the data

For literally anything in this project to run, you /need/ the following packages:

- [[https://www.python.org/][Python 3.11+]]
- [[https://pytorch.org/][PyTorch]]
- ~bash~
- ~curl~
- ~magick~

Set up the venv with ~source venv/bin/activate~ or however you activate with your specific shell.

* What is left to do?

1. Add a bunch of IMSLP scores to ~imslp_urls.txt~
   - Note: the URL should be to the actual pdf file, ending in ~.pdf~.
2. Make my code not a jumbled spaghetti mess of garbage that works on a prayer
3. Write the neural network (done. thanks perplexity ;)
4. Make the stitcher
5. Generalize the code, so the very specific functions like [[file:src/chunker.py][chunker.py]] work in the more generalized circumstances that they need to work in
   - Chiefly, just change the path to chunk to, not just ~data/images/chunks~
6. Make a ~requirements.txt~ with pip so dependencies can be ~pip install -r requirements.txt~'d
7. Hope it's better than traditional general-purpose upscaling techniques in some manner
8. Write a paper
9. Profit
