#+title: COSC 200
#+author: Jason Press

This is Jason Press and Mia Stulac's project for COSC 200. Although I don't know if Mia Stulac is caring about this anymore, so I guess it's just Jason Press (?)

This project is training a neural network to upscale scanned scores.

* Setup the data

For literally anything in this project to run, you /need/ the following packages:

- [[https://www.python.org/][Python 3.11+]]
- [[https://pytorch.org/][PyTorch]]
- ~bash~

NOTE: ~musescore_bootstrap.py~ is being depricated in favor of ~imslp_bootstrap.py~.

For ~imslp_bootstrap.py~ to run, you need the following packages:

- ~curl~

Yeah that's it.

For ~musescore_bootstrap.py~ to run, the following packages must be installed (note: versions can be earlier, I just don't care to find out what versions are good):

- [[https://musescore.org/en][Musescore 4.3+]]
- [[https://nodejs.org/en][Node.js]] (or npx)

You can check if the packages are installed by running the following commands:

#+begin_src:
mscore --version
npx --version
python3 --version
#+end_src

Git clone this repo.

Ensure ~dl-librescore~ is installed by running ~npx dl-librescore~. If this is the first time running it, it should install some packages and do its thing. Once a dialog appears asking for a file, you can stop the process (~C-c~).

Ensure ~mscore~ is a part of ~$PATH~. If ~mscore --version~ shows a version of Musescore, then you're good. If not, add it to your ~$PATH~.

Run ~src/bootstrap.py~ (you can execute ~python3 bootstrap.py~ in the src directory). It will create the ~/data~ directory inside the project.

* What is left to do?

1. Add a bunch of IMSLP scores to ~imslp_urls.txt~
   - Note: the URL should be to the actual pdf file, ending in ~.pdf~.
2. Write a Python script that converts the high quality images to low quality images
   - Divide pdf files high quality images
   - Then the high quality images into ~n x n~ regions
   - Then the high quality squares into low quality squares
3. Write the neural network
   - This /might/ require dividing the image into regions, upscaling each region, and then stitching them back together. If so, find out how to do this
5. Hope it's better than traditional general-purpose upscaling techniques in some manner
6. Write a paper
7. Profit
